try:
  # intentamos correr este c√≥digo
  # puede haber errores
  resultado = 10 + 10
  print(resultado)
except:
  # en caso de que exista error se va por aqui
  print('Parece que hay un error, escribir bien las variables')